name: 'Actions AWS Function for Node'
description: 'Provision and AWS function'
inputs:
  artifacts:
    description: Folder where module will be installed
outputs: 
  entrypoint-file: 
    description: "Name for the module file"
    value: entry.js
  entrypoint-handler: 
    description: "Name of the function's handler"
    value: handler
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
        with:
          node-version: 20
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: npm install
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: mv node_modules ./dist/
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: mv routes.yaml ./dist/
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: npx shadow-cljs release app
        