# .github/workflows/on-push-main.yml
name: demo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment:
      name: main
      url: ${{ steps.backend.outputs.url }}
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.actor }}
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: sample
      - uses: alonch/actions-aws-http-node@main
        id: http  
        with:
          artifacts: dist
      - uses: alonch/actions-aws-function-node@main
        id: backend
        with: 
          name: actions-aws-http-node
          artifacts: dist
          entrypoint-file: ${{ steps.http.outputs.entrypoint-file }}
          entrypoint-function: ${{ steps.http.outputs.entrypoint-function }}
          allow-public-access: true
          timeout: 60
      

