name: Node.js Package

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm version ${{ github.ref_name }} --no-git-tag-version
      - run: npm install
      - run: npx shadow-cljs release app
      - env:       
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
      - run: npm publish
        env:       
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          